// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// The tmux plugin's self-contained declaration contract. Terminal and agent
// channel payloads use sdk/schema/agent_control.cue directly; this plugin does
// not duplicate those wire shapes.
type TmuxPlugin struct {
	Providers []any/* CUE closed list */ `yaml:"providers,omitempty" json:"providers"`

	Contract string `yaml:"contract,omitempty" json:"contract"`
}
